//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public System.DateTime Date_start { get; set; }
        public Nullable<System.DateTime> Date_end { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Passport_data { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
    }
}
