//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFekzam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersDetail = new HashSet<OrdersDetail>();
        }
    
        public int Id { get; set; }
        public string Order_details { get; set; }
        public string Order_status { get; set; }
        public string Waybill_num { get; set; }
        public decimal Sum_final { get; set; }
        public decimal Sum_payed { get; set; }
        public System.DateTime Order_date { get; set; }
        public System.DateTime Date_send { get; set; }
        public Nullable<System.DateTime> Date_arrive { get; set; }
        public string Delivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetail { get; set; }
    }
}
