//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFekzam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrdersDetail = new HashSet<OrdersDetail>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string ART { get; set; }
        public string Catalogue_num { get; set; }
        public string Manufacturer { get; set; }
        public decimal Price_first { get; set; }
        public decimal Price_sale { get; set; }
        public string Color { get; set; }
        public int Product_rest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetail { get; set; }
    }
}
