//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFekzam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategorry
    {
        public int Id { get; set; }
        public string CategoryExtra { get; set; }
    }
}
